apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nexora
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - api-deployment.yaml
  - worker-deployment.yaml
  - web-deployment.yaml
  - services.yaml
  - availability.yaml
  - networkpolicy.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
